### ISSUE TITLE
Breaking typo in pixi-extension.js @ L86

### ISSUE THREAD

**Issue by Slynchy** [ErikSom/gamestats#4]
Typo on line 86 of `pixi-extension.js` incorrectly calculates buffer usage in MB.

https://github.com/ErikSom/gamestats/blob/main/src/pixi-extension.js#L86

**Comment by ErikSom** [comment]
What would be the correct way to do this?

**Comment by ErikSom** [comment]
Ahh @Slynchy I see the typo now! Thanks!
